### ISSUE TITLE
Register Vendor ID

### ISSUE THREAD

**Issue by aaronbell** [noriokanisawa/HachiMaruPop#1]
It appears you do not have a [registered vendor ID](https://docs.microsoft.com/en-us/typography/vendors/) from Microsoft. Please [apply for one](https://docs.microsoft.com/en-us/typography/vendors/register).

**Comment by noriokanisawa** [comment]
Hello, I'm the author.
There are many things I can't say at this point, but I'm going to close this job.
Of course, as long as I have accepted this project, I will do what I should do.
However, I am in a state of being mentally cornered, and it takes time to proceed with work and understand the text.
I think it will take some time before you can understand the vendor ID. I'm sorry.

**Comment by aaronbell** [comment]
Thank you for registering `nkan`
