### ISSUE TITLE
壟 typo

### ISSUE THREAD

**Issue by max32002** [noriokanisawa/HachiMaruPop#14]
![Screen Shot 2021-09-04 at 3 47 56 AM](https://user-images.githubusercontent.com/4498233/132058690-cc25f3ad-33bc-445e-8164-cddcd28c1384.png)

**Comment by noriokanisawa** [comment]
Fixed.

**Comment by max32002** [comment]
Thank you very much.

noriokanisawa ***@***.***> 於 2021年9月4日 週六 下午12:35 寫道：

**Comment by max32002** [comment]
![Screen Shot 2021-09-06 at 12 26 21 AM](https://user-images.githubusercontent.com/4498233/132134152-8a7ce82e-7c5f-4bf3-aefb-ad42d1d4752f.png)
