### ISSUE TITLE
捗 typo

### ISSUE THREAD

**Issue by max32002** [noriokanisawa/HachiMaruPop#15]
![Screen Shot 2021-09-10 at 7 02 06 AM](https://user-images.githubusercontent.com/4498233/132773660-df4e37fa-9c20-4e75-9d9a-5bb2c9eded5f.png)

**Comment by noriokanisawa** [comment]
Fixed.

**Comment by max32002** [comment]
thank you very much.👍

noriokanisawa ***@***.***> 於 2021年9月11日 週六 上午7:47 寫道：

**Comment by max32002** [comment]
![Screen Shot 2021-09-14 at 10 17 35 PM](https://user-images.githubusercontent.com/4498233/133274747-90955875-b964-4907-ad4d-0b68b4b1ce25.png)
