### ISSUE TITLE
瞥 typo

### ISSUE THREAD

**Issue by max32002** [noriokanisawa/HachiMaruPop#16]
The component in the upper right corner is different.
(右上隅のコンポーネントが異なります)
![Screen Shot 2021-09-26 at 8 25 20 AM](https://user-images.githubusercontent.com/4498233/134789138-b942ef6e-237b-48ef-bd43-5aba0ef0bdd6.png)

**Comment by noriokanisawa** [comment]
Fixed.

**Comment by max32002** [comment]
thank you very much.

noriokanisawa ***@***.***> 於 2021年9月26日 週日 下午5:21 寫道：

**Comment by max32002** [comment]
<img width="249" alt="Screen Shot 2021-10-05 at 12 06 34 PM" src="https://user-images.githubusercontent.com/4498233/135958570-0fcb304a-a415-4a6b-a185-29e112a7134e.png">

**Comment by max32002** [comment]
Noto Sans CJK JP

<img width="589" alt="Screen Shot 2021-10-05 at 12 13 32 PM" src="https://user-images.githubusercontent.com/4498233/135959072-e07f460b-07ca-45d6-b6e8-d80b2d2a3714.png">

**Comment by noriokanisawa** [comment]
I'm sorry I didn't notice the component in the upper right.
Fixed.

**Comment by max32002** [comment]
thank you very much.

**Comment by max32002** [comment]
Looks very good.
![Screen Shot 2021-10-06 at 9 52 02 PM](https://user-images.githubusercontent.com/4498233/136216285-cc123281-8ce0-48f8-abf1-0df9a90a9b0c.png)
