### ISSUE TITLE
隆 typo

### ISSUE THREAD

**Issue by max32002** [noriokanisawa/HachiMaruPop#22]
current:
![Screen Shot 2022-05-13 at 5 10 50 AM](https://user-images.githubusercontent.com/4498233/168168899-00c89f15-823f-41bd-91a8-b4a51c4278d9.png)

**Comment by noriokanisawa** [comment]
When using it in Japan, this glyph should match, but where is the correction?

**Comment by max32002** [comment]
Yes, you are right. I got another version at uniF9DC.
<img width="412" alt="Screen Shot 2022-05-16 at 4 14 37 PM" src="https://user-images.githubusercontent.com/4498233/168548947-98195431-b320-4394-b945-a9e9bed5a9ba.png">
